<?php

return [
    'background' => [
        'body'        => 'bg-body',
        'danger'      => 'bg-danger',
        'dark'        => 'bg-dark',
        'info'        => 'bg-info',
        'light'       => 'bg-light',
        'primary'     => 'bg-primary',
        'secondary'   => 'bg-secondary',
        'success'     => 'bg-success',
        'transparent' => 'bg-transparent',
        'warning'     => 'bg-warning',
        'white'       => 'bg-white',
    ],
    'text' => [
        'black-50'  => 'text-black-50',
        'body'      => 'text-body',
        'danger'    => 'text-danger',
        'dark'      => 'text-dark',
        'info'      => 'text-info',
        'light'     => 'text-light',
        'muted'     => 'text-muted',
        'primary'   => 'text-primary',
        'secondary' => 'text-secondary',
        'success'   => 'text-success',
        'warning'   => 'text-warning',
        'white-50'  => 'text-white-50',
        'white'     => 'text-white',
    ],
    'border' => [
        'danger'    => 'border-danger',
        'dark'      => 'border-dark',
        'info'      => 'border-info',
        'light'     => 'border-light',
        'primary'   => 'border-primary',
        'secondary' => 'border-secondary',
        'success'   => 'border-success',
        'warning'   => 'border-warning',
        'white'     => 'border-white',
    ],
    'button' => [
        'danger'    => 'btn-danger',
        'dark'      => 'btn-dark',
        'info'      => 'btn-info',
        'light'     => 'btn-light',
        'link'      => 'btn-link',
        'primary'   => 'btn-primary',
        'secondary' => 'btn-secondary',
        'success'   => 'btn-success',
        'warning'   => 'btn-warning',
    ],
    'button_outline' => [
        'danger'    => 'btn-outline-danger',
        'dark'      => 'btn-outline-dark',
        'info'      => 'btn-outline-info',
        'light'     => 'btn-outline-light',
        'link'      => 'btn-outline-link',
        'primary'   => 'btn-outline-primary',
        'secondary' => 'btn-outline-secondary',
        'success'   => 'btn-outline-success',
        'warning'   => 'btn-outline-warning',
    ],
    'table' => [
        'danger'    => 'table-danger',
        'dark'      => 'table-dark',
        'info'      => 'table-info',
        'light'     => 'table-light',
        'primary'   => 'table-primary',
        'secondary' => 'table-secondary',
        'success'   => 'table-success',
        'warning'   => 'table-warning',
    ],
    'link' => [
        'danger'    => 'link-danger',
        'dark'      => 'link-dark',
        'info'      => 'link-info',
        'light'     => 'link-light',
        'primary'   => 'link-primary',
        'secondary' => 'link-secondary',
        'success'   => 'link-success',
        'warning'   => 'link-warning',
    ],
    'list_group_item' => [
        'danger'    => 'list-group-item-danger',
        'dark'      => 'list-group-item-dark',
        'info'      => 'list-group-item-info',
        'light'     => 'list-group-item-light',
        'primary'   => 'list-group-item-primary',
        'secondary' => 'list-group-item-secondary',
        'success'   => 'list-group-item-success',
        'warning'   => 'list-group-item-warning',
    ],
    'alert' => [
        'danger'    => 'alert-danger',
        'dark'      => 'alert-dark',
        'info'      => 'alert-info',
        'light'     => 'alert-light',
        'primary'   => 'alert-primary',
        'secondary' => 'alert-secondary',
        'success'   => 'alert-success',
        'warning'   => 'alert-warning',
    ],
    'theme' => [
        'primary',
        'secondary',
        'success',
        'warning',
        'danger',
        'info',
        'dark',
        'light',
    ],
];
