<?php

return (object) [
    'arrow_left_circle_fill' => '<i class="bi bi-arrow-left-circle-fill"></i>',
    'arrow_left_circle' => '<i class="bi bi-arrow-left-circle"></i>',
    'arrow_left_return_down' => '<i class="bi bi-arrow-return-left"></i>',
    'arrow_left_return_up' => '<i class="bi bi-arrow-90deg-left"></i>',
    'arrow_left_short' => '<i class="bi bi-arrow-left-short"></i>',
    'arrow_left' => '<i class="bi bi-arrow-left"></i>',
    'arrow_right_circle_fill' => '<i class="bi bi-arrow-right-circle-fill"></i>',
    'arrow_right_circle' => '<i class="bi bi-arrow-right-circle"></i>',
    'arrow_right_return_down' => '<i class="bi bi-arrow-return-right"></i>',
    'arrow_right_return_up' => '<i class="bi bi-arrow-90deg-right"></i>',
    'arrow_right_short' => '<i class="bi bi-arrow-right-short"></i>',
    'arrow_right' => '<i class="bi bi-arrow-right"></i>',
    'eye_fill' => '<i class="bi bi-eye-fill"></i>',
    'eye_not_fill' => '<i class="bi bi-eye-slash-fill"></i>',
    'eye_not' => '<i class="bi bi-eye-slash"></i>',
    'eye' => '<i class="bi bi-eye"></i>',
    'pen_fill' => '<i class="bi bi-pen-fill"></i>',
    'pen' => '<i class="bi bi-pen"></i>',
    'pencil_fill' => '<i class="bi bi-pencil-fill"></i>',
    'pencil_square' => '<i class="bi bi-pencil-square"></i>',
    'pencil' => '<i class="bi bi-pencil"></i>',
    'plis_circle_fill' => '<i class="bi bi-plus-circle-fill"></i>',
    'plus_circle' => '<i class="bi bi-plus-circle"></i>',
    'plus_square_fill' => '<i class="bi bi-plus-square-fill"></i>',
    'plus_square' => '<i class="bi bi-plus-square"></i>',
    'plus' => '<i class="bi bi-plus fw-bold"></i>',
    'printer-fill' => '<i class="bi bi-printer-fill"></i>',
    'printer' => '<i class="bi bi-printer"></i>',
];
